# Generated by Django 4.0 on 2022-04-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='discussion',
        ),
    ]
